Repository yays-or-nays/yays-or-nays-FE, pull requests merged in 2021-04, with the labels that each got.

#8 Feature/landing page
  ios/Launch Screen.storyboard
  ios/Podfile.lock
  ios/Pods/Local Podspecs/FBReactNativeSpec.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/yaysornays.xcodeproj/project.pbxproj
  ios/yaysornays.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/yaysornays/AppDelegate.m
  ios/yaysornays/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/yaysornays/Images.xcassets/Contents.json
  ios/yaysornays/Images.xcassets/Image.imageset/Contents.json
  ios/yaysornays/Images.xcassets/Image.imageset/appLogo.png
  ios/yaysornays/Info.plist
  ios/yaysornays/LaunchScreen.storyboard
  src/App.js
  src/LandingPage/Welcome.js
  src/NavBar/NavBar.js
Labels: enhancement

#10 Feature/how to
  ios/Podfile.lock
  ios/Pods/Local Podspecs/FBReactNativeSpec.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/yaysornays/Images.xcassets/Image.imageset/appLogo.png
  package-lock.json
  package.json
  src/App.js
  src/Categories/Categories.js
  src/LandingPage/HowTo.js
  src/LandingPage/Welcome.js
  src/NavBar/NavBar.js
Labels: enhancement

#17 Feature/redux
  .detoxrc.json
  e2e/config.json
  e2e/environment.js
  e2e/firstTest.e2e.js
  index.js
  ios/Podfile.lock
  ios/Pods/Local Podspecs/FBReactNativeSpec.podspec.json
  ios/Pods/Local Podspecs/RNCMaskedView.podspec.json
  ios/Pods/Local Podspecs/react-native-safe-area-context.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/App.js
  src/Categories/Categories.js
  src/HotTakes/HotTakes.js
  src/LandingPage/HowTo.js
  src/LandingPage/Welcome.js
  src/NavBar/NavBar.js
  src/Redux/Actions/categories.js
  src/Redux/Actions/hotTakes.js
  src/Redux/Reducers/categories.js
  src/Redux/Reducers/hotTakes.js
  src/Redux/store.js
  src/util.js
Labels: Redux, enhancement

#18 Feature/hot take styling
  src/HotTakes/HotTakes.js
  src/LandingPage/HowTo.js
  src/assets/categories.png
  src/assets/hotTakes.png
  src/assets/results.png
Labels: enhancement

#20 Add tests for the landing page of the app.
  e2e/firstTest.e2e.js
  e2e/landingPage.e2e.js
  src/LandingPage/HowTo.js
  src/LandingPage/Welcome.js
Labels: testing

#22 Detox/categories
  e2e/Categories.e2e.js
  package.json
  src/LandingPage/HowTo.js
Labels: testing

#23 Feature/test hot takes component
  e2e/HotTake.e2e.js
  ios/Podfile.lock
  ios/Pods/Local Podspecs/FBReactNativeSpec.podspec.json
  ios/Pods/Local Podspecs/RNCMaskedView.podspec.json
  ios/Pods/Local Podspecs/react-native-safe-area-context.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  src/HotTakes/HotTakes.js
Labels: documentation, testing
